---
- hosts: default
  user: "{{ lookup('env','USERNSSH') }}"

  tasks:
    #Instalacion requisitos
  - name: Actualizar
    apt: update_cache=yes

  - name: Instalar buildessential
    apt: name=build-essential state=present

  - name: Install git
    apt: name=git state=present

  - name: Borrar si Actualiza
    shell: rm -rf InsertaLogo

  - name: Clonar InsertaLogo
    git: repo=https://github.com/magvugr/InsertaLogo.git dest=InsertaLogo clone=yes force=yes

  - name: InstalarPip
    apt: name=python-pip state=present

  - name: InstalarPip Dev
    apt: name=python-dev state=present

  - name: InstalarPip libpq-dev
    apt: name=libpq-dev state=present

  - name: Install
    shell: cd InsertaLogo/ && make installa
